import {MATERIALS,PIECES,aimedObject} from './building.js';
const paths={wood:'M8 4 24 8 24 24 8 28 2 23 2 9ZM8 4V28M2 9 8 13 24 8M8 19 24 14',brick:'M2 10 20 4 30 10 12 17ZM2 10V22L12 28 30 21V10M12 17V28M20 14V24',metal:'M5 5H27V12H21V23H27V29H5V23H11V12H5Z',wall:'M3 4H29V29H3ZM3 12H29M3 21H29M12 4V12M21 12V21M12 21V29',floor:'M2 18 17 7 31 15 16 28ZM9 12 24 22M9 24 24 11',stairs:'M2 29V23H9V17H16V11H23V5H30V29Z',roof:'M2 24 16 5 30 24 16 30ZM16 5V30'};
export const buildIcon=name=>`<svg viewBox="0 0 32 32" aria-hidden="true"><path d="${paths[name]}"/></svg>`;
export class BuildingUI{
 constructor(root,controls,send){this.controls=controls;this.send=send;this.edit=null;
 root.insertAdjacentHTML('beforeend',`<div class="build-hud"><div class="build-materials">${Object.keys(MATERIALS).map(m=>`<button data-material="${m}" aria-label="Build with ${m}">${buildIcon(m)}<b id="material-${m}">0</b></button>`).join('')}</div><div class="build-pieces">${PIECES.map((p,i)=>`<button data-piece="${p}" aria-label="Build ${p}">${buildIcon(p)}<kbd>${['Z','C','V','B'][i]}</kbd></button>`).join('')}</div><div><button class="build-toggle" data-build-control="toggle">BUILD <kbd>H</kbd></button><button data-build-control="rotate">ROTATE</button><button data-build-control="edit">EDIT</button><button data-build-control="repair">REPAIR</button></div></div><div class="build-help" hidden></div><div class="build-target" hidden></div><div class="build-edit" hidden><strong>EDIT STRUCTURE</strong><div class="build-edit-grid"></div><div><button data-build-control="confirm">CONFIRM</button><button data-build-control="reset">RESET</button><button data-build-control="cancel">CANCEL</button></div></div><div class="harvest-gain" role="status"></div>`);
 this.root=root;
 root.addEventListener('click',e=>{const material=e.target.closest('[data-material]'),piece=e.target.closest('[data-piece]'),action=e.target.closest('[data-build-control]'),cell=e.target.closest('[data-edit-cell]');if(material)controls.buildMaterial=material.dataset.material;if(piece){controls.buildType=piece.dataset.piece;controls.buildMode=true;}if(action)this.action(action.dataset.buildControl);if(cell&&this.edit){this.edit.mask^=1<<Number(cell.dataset.editCell);this.renderEdit();}});
 }
 action(action){const c=this.controls;if(action==='toggle'){c.buildMode=!c.buildMode;this.cancel();}if(action==='rotate')c.buildRotation=(c.buildRotation+1)%4;if(action==='material')c.buildMaterial=Object.keys(MATERIALS)[(Object.keys(MATERIALS).indexOf(c.buildMaterial)+1)%3];if(action==='cancel')this.cancel();if(action==='reset'&&this.edit){this.edit.mask=0;this.renderEdit();}if(action==='confirm'&&this.edit){this.send('build-edit-'+this.edit.mask+'-'+this.edit.id);this.cancel();}if(['confirm','cancel'].includes(action))document.dispatchEvent(new Event('build-edit-close'));}
 cancel(){this.edit=null;this.controls.editing=false;this.root.querySelector('.build-edit').hidden=true;}
 beginEdit(state,p,map){const target=aimedObject(map,p,8),b=state.royale.builds.find(b=>b.id===target?.box.buildId);if(!b||b.owner!==p.id)return false;this.edit={...b};this.controls.editing=true;this.controls.editTarget=b.id;this.renderEdit();return true;}
 renderEdit(){const e=this.edit,grid=this.root.querySelector('.build-edit-grid');this.root.querySelector('.build-edit').hidden=false;const count=e.type==='wall'?9:e.type==='stairs'?2:4;grid.style.gridTemplateColumns=`repeat(${count===9?3:2},1fr)`;grid.innerHTML=Array.from({length:count},(_,i)=>{const cell=count===9?(2-Math.floor(i/3))*3+i%3:i;return `<button data-edit-cell="${cell}" class="${e.mask&(1<<cell)?'removed':''}" aria-label="Toggle section ${cell+1}" aria-pressed="${!!(e.mask&(1<<cell))}"></button>`;}).join('');}
 update(state,p,map,label){
 const gain=this.root.querySelector('.harvest-gain'),harvest=p.lastHarvest;gain.textContent=harvest&&state.time-harvest.time<1.3?'+'+harvest.amount+' '+harvest.material.toUpperCase():'';
 for(const m of Object.keys(MATERIALS)){this.root.querySelector('#material-'+m).textContent=p.materials?.[m]||0;this.root.querySelector(`[data-material="${m}"]`).classList.toggle('selected',this.controls.buildMaterial===m);}
 for(const type of PIECES)this.root.querySelector(`[data-piece="${type}"]`).classList.toggle('selected',this.controls.buildMode&&this.controls.buildType===type);
 for(const [type,key]of [['wall','buildWall'],['floor','buildFloor'],['stairs','buildStairs'],['roof','buildRoof']])this.root.querySelector(`[data-piece="${type}"] kbd`).textContent=label(key);
 const help=this.root.querySelector('.build-help'),c=this.controls;help.hidden=!c.buildMode||p.health<=0;help.textContent=`${c.reason||'10 '+c.buildMaterial.toUpperCase()+' · '+c.buildType.toUpperCase()} · ${label('fire')} BUILD · ${label('buildRotate')} ROTATE · ${label('buildMaterial')} MATERIAL`;
 const hit=aimedObject(map,p,8),b=state.royale.builds?.find(b=>b.id===hit?.box.buildId),health=b||state.royale.worldDamage?.[hit?.box.objectId];const target=this.root.querySelector('.build-target');target.hidden=!hit||p.health<=0;
 if(hit)target.innerHTML=`<b>${b?b.type.toUpperCase():hit.box.material.toUpperCase()}</b><div><i style="width:${health?Math.max(0,health.health/health.maxHealth*100):100}%"></i></div><span>${Math.ceil(health?.health??(hit.box.kind==='tree'?250:hit.box.kind==='prop'?180:450))} HP${b?.owner===p.id?' · '+label('buildEdit')+' EDIT · '+label('buildRepair')+' REPAIR':''}</span>`;
 if(this.edit&&!state.royale.builds.some(b=>b.id===this.edit.id))this.cancel();
 }
}
