import { safeName } from './moderation.js';
export const VERSION = 6;
export const WEAPONS = [
  {
    id: "sprinter",
    basedOn: "EggK-47",
    reloadEmpty: 3.433333333333333,
    ammoPickup: 30,
    automatic: true,
    spreadMax: 0.15,
    shotBloom: 0.05,
    spreadRecovery: 0.025,
    aimSpread: 0.5,
    movementSpread: 1,
    muzzle: 0.9,
    sightY: 0.285,
    boltSpeed: 45.0,
    gravity: 0,
    optic: "reflex",
    name: "Sprinter",
    role: "ASSAULT",
    desc: "A steady all-rounder. Fast, accurate, dependable.",
    damage: 30,
    interval: 0.1,
    magazine: 30,
    reserve: 240,
    reload: 2.6666666666666665,
    spread: 0.03,
    pellets: 1,
    speed: 7.4,
    range: 20,
    color: 0xf8b829,
    size: 1,
    zoom: 65,
  },
  {
    id: "scatter",
    basedOn: "Scrambler",
    reloadEmpty: 2.6,
    ammoPickup: 8,
    automatic: false,
    spreadMax: 0.16,
    shotBloom: 0.17,
    spreadRecovery: 0.02,
    aimSpread: 0.6,
    movementSpread: 0.2,
    muzzle: 0.9,
    sightY: 0.22,
    boltSpeed: 30,
    gravity: 0,
    optic: "iron",
    name: "Scatter",
    role: "SCATTER",
    desc: "Get close. One wide burst, plenty of punch.",
    damage: 8.5,
    interval: 0.26666666666666666,
    magazine: 2,
    reserve: 24,
    reload: 2.6,
    spread: 0.13,
    pellets: 20,
    speed: 7.4,
    range: 8,
    color: 0xf47b57,
    size: 1.1,
    zoom: 70,
  },
  {
    id: "needle",
    basedOn: "Crackshot",
    reloadEmpty: 2.4,
    ammoPickup: 4,
    automatic: false,
    spreadMax: 0.35,
    shotBloom: 0.1,
    spreadRecovery: 0.023,
    aimSpread: 0.5,
    movementSpread: 1.3,
    muzzle: 1.1,
    sightY: 0.285,
    boltSpeed: 60,
    gravity: 0,
    optic: "scope",
    magnification: 3.5,
    name: "Needle",
    role: "PRECISION",
    desc: "One powerful scoped shot, then reload.",
    damage: 170,
    interval: 0.5,
    magazine: 1,
    reserve: 12,
    reload: 2.4,
    spread: 0,
    pellets: 1,
    speed: 7.4,
    range: 60,
    color: 0x57c9df,
    size: 1.35,
    zoom: 27,
  },
  {
    id: "zipper",
    basedOn: "Whipper",
    reloadEmpty: 3.7666666666666666,
    ammoPickup: 40,
    automatic: true,
    spreadMax: 0.19,
    shotBloom: 0.045,
    spreadRecovery: 0.05,
    aimSpread: 0.6,
    movementSpread: 0.7,
    muzzle: 0.68,
    sightY: 0.285,
    boltSpeed: 37.5,
    gravity: 0,
    optic: "reflex",
    name: "Zipper",
    role: "RAPID",
    desc: "Move quickly and keep a stream of shots flying.",
    damage: 23,
    interval: 0.06666666666666667,
    magazine: 40,
    reserve: 200,
    reload: 3.1666666666666665,
    spread: 0.06,
    pellets: 1,
    speed: 7.4,
    range: 20,
    color: 0xb6db56,
    size: 0.78,
    zoom: 68,
  },
  {
    id: "thumper",
    basedOn: "RPEGG",
    reloadEmpty: 2.8333333333333335,
    ammoPickup: 1,
    automatic: false,
    spreadMax: 0.3,
    shotBloom: 0.3,
    spreadRecovery: 0.02,
    aimSpread: 0.5,
    movementSpread: 1,
    splashRadius: 2.75,
    minRange: 3,
    muzzle: 0.74,
    sightY: 0.285,
    boltSpeed: 12.0,
    gravity: 0,
    optic: "reflex",
    name: "Thumper",
    role: "LAUNCHER",
    desc: "A straight rocket that arms after three units of flight.",
    damage: 140,
    interval: 1.3333333333333333,
    magazine: 1,
    reserve: 3,
    reload: 2.8333333333333335,
    spread: 0.015,
    pellets: 1,
    speed: 7.4,
    range: 45,
    color: 0xcb8cec,
    size: 1.3,
    zoom: 65,
    projectile: true,
  },
  {
    id: "anchor",
    basedOn: "Free Ranger",
    reloadEmpty: 3.7666666666666666,
    ammoPickup: 15,
    automatic: false,
    spreadMax: 0.3,
    shotBloom: 0.3,
    spreadRecovery: 0.025,
    aimSpread: 0.5,
    movementSpread: 1,
    muzzle: 0.94,
    sightY: 0.285,
    boltSpeed: 52.5,
    gravity: 0,
    optic: "scope",
    name: "Anchor",
    role: "MARKSMAN",
    desc: "A scoped semi-automatic rifle for deliberate follow-up shots.",
    damage: 105,
    interval: 0.43333333333333335,
    magazine: 15,
    reserve: 60,
    reload: 2.7666666666666666,
    spread: 0.004,
    pellets: 1,
    speed: 7.4,
    range: 50,
    color: 0x6dafcf,
    size: 1.3,
    zoom: 35,
  },
  {
    id: "duet",
    basedOn: "Tri-Hard",
    reloadEmpty: 3.433333333333333,
    ammoPickup: 24,
    automatic: false,
    spreadMax: 0.15,
    shotBloom: 0.037,
    spreadRecovery: 0.03,
    aimSpread: 0.6,
    movementSpread: 0.8,
    muzzle: 0.92,
    sightY: 0.285,
    boltSpeed: 45.0,
    gravity: 0,
    optic: "prism",
    magnification: 1.8,
    name: "Duet",
    role: "BURST",
    desc: "Three precise shots with each trigger press.",
    damage: 32,
    interval: 0.5,
    burst: 3,
    burstInterval: 0.1,
    magazine: 24,
    reserve: 150,
    reload: 2.6666666666666665,
    spread: 0.03,
    pellets: 1,
    speed: 7.4,
    range: 20,
    color: 0xf1d368,
    size: 0.95,
    zoom: 58,
  },
  {
    id: "pip",
    basedOn: "Cluck 9mm",
    reloadEmpty: 3.2666666666666666,
    ammoPickup: 15,
    automatic: false,
    spreadMax: 0.15,
    shotBloom: 0.09,
    spreadRecovery: 0.08,
    aimSpread: 0.8,
    movementSpread: 0.6,
    muzzle: 0.45,
    sightY: 0.22,
    boltSpeed: 30,
    gravity: 0,
    optic: "iron",
    name: "Pip",
    role: "SIDEARM",
    desc: "A dependable backup for every loadout.",
    damage: 26,
    interval: 0.13333333333333333,
    magazine: 15,
    reserve: 60,
    reload: 2.6666666666666665,
    spread: 0.035,
    pellets: 1,
    speed: 7.4,
    range: 15,
    color: 0xf2e5ba,
    size: 0.6,
    zoom: 65,
    secondary: true,
  },
];
export const MODES = [
  {
    id: "ffa",
    name: "Free for all",
    short: "FFA",
    description: "Every egg for itself. First to 20 eliminations.",
    limit: 20,
    teams: false,
  },
  {
    id: "teams",
    name: "Team scramble",
    short: "TEAMS",
    description: "Coral versus blue. First team to 35 eliminations.",
    limit: 35,
    teams: true,
  },
  {
    id: "capture",
    name: "Capture the crown",
    short: "CAPTURE",
    description:
      "Bring the other team’s crown home. Your crown must be at base. First to 3.",
    limit: 3,
    teams: true,
  },
  {
    id: "control",
    name: "Sunny side",
    short: "CONTROL",
    description: "Hold the golden zone with your team. First to 90 points.",
    limit: 90,
    teams: true,
  },
];
export const COLORS = [
  "#fff6da",
  "#f9b74a",
  "#72cfdd",
  "#ee897b",
  "#a5d76e",
  "#b7a1ec",
  "#8492a6",
  "#fae8b6",
  "#ffffff", "#273345", "#ff637e", "#d94949", "#f78336", "#ffe45e",
  "#45b979", "#21796d", "#80eacb", "#3d8ce8", "#464eb3", "#8c54c9",
  "#efb4df", "#bd728b", "#946344", "#b9ccd4",
];
export const HATS = ["No headwear", "Headphones", "Cap", "Crown", "Sprout", "Top hat", "Beanie", "Wizard", "Cowboy", "Party hat", "Halo", "Bunny ears", "Cat ears", "Chef", "Beret", "Antenna", "Flower", "Viking", "Pirate", "Propeller"];
export const PATTERNS = ["No pattern", "Stripes", "Polka dots", "Checkerboard", "Confetti", "Lightning", "Stars", "Two tone", "Waves", "Diamond"];
export const FINISHES = ["Classic", "Matte", "Gloss", "Metallic"];
export const EYEWEAR = ["Classic visor", "Round goggles", "Sunglasses", "Cyclops", "Square glasses", "Star shades", "No eyewear"];
// Append the plain option so existing saved eyewear IDs keep their meaning.
export const NO_EYEWEAR = 6;
const cosmeticIndex = (value, options) => Number.isInteger(Number(value)) && Number(value) >= 0 && Number(value) < options.length ? Number(value) : 0;
export const TEAM_COLORS = [0x47c5e0, 0xfb7f70];
export const clamp = (n, a, b) => Math.max(a, Math.min(b, n));
export const weapon = (id) => WEAPONS.find((w) => w.id === id) || WEAPONS[0];
export const gun = (p) => weapon(p.slot === 1 ? "pip" : p.weapon);
export const mode = (id) => MODES.find((m) => m.id === id) || MODES[0];
export const cleanName = safeName;
export function safeProfile(p = {}) {
  if (!p || typeof p !== 'object') p = {};
  return {
    name: cleanName(p.name),
    weapon: weapon(p.weapon).secondary ? "sprinter" : weapon(p.weapon).id,
    color: COLORS.includes(p.color) ? p.color : COLORS[0],
    hat: cosmeticIndex(p.hat, HATS),
    pattern: cosmeticIndex(p.pattern, PATTERNS),
    finish: cosmeticIndex(p.finish, FINISHES),
    eyewear: cosmeticIndex(p.eyewear, EYEWEAR),
    accent: COLORS.includes(p.accent) ? p.accent : COLORS[1],
  };
}
export function rng(seed) {
  let s = seed >>> 0;
  return () => {
    s += 0x6d2b79f5;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t ^= t + Math.imul(t ^ (t >>> 7), 61 | t);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
